### ISSUE TITLE
Issue in running sample c_api example

### ISSUE THREAD

**Issue by HackersSpirit** [Neargye/hello_tf_c_api#10]
Hello @Neargye :
I have download the pre-built tensorflow lib file from your github link and trying to run the sample program on Windows 10 64-built.
I am getting the following error:
main.obj : error LNK2019: unresolved external symbol __imp_TF_Version referenced in function main
I am running the program using qt creator please find the details:
Pro file(Linking the library and defining the include path):

INCLUDEPATH +=C:\\Users\\jhon\\Downloads\\sample\\include
LIBS += -LC:\\Users\\jhon\\Downloads\\sample\\lib
        -ltensorflow

Sample Program:
```
#include <QCoreApplication>
#if defined(_MSC_VER) && !defined(COMPILER_MSVC)
#  define COMPILER_MSVC // Set MSVC visibility of exported symbols in the shared library.
#endif

#if defined(_MSC_VER)
#  pragma warning(push)
#  pragma warning(disable : 4996)
#  pragma warning(disable : 4190)
#endif

#include <tensorflow/c/c_api.h> // TensorFlow C API header
#include <iostream>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    std::cout << "TensorFlow Version: " << TF_Version() << std::endl;

    return a.exec();
}
```
Actually i am facing this issue with all the dll's which i have downloaded.
I want to know whether its issue of the dll or i am doing some silly mistake to run the program

**Comment by HackersSpirit** [comment]
No, I did not use cmake I downloaded the following folder: libtensorflow-cpu-windows-x86_64-1.11.0.zip
I have linked all the dll in my pro file.
I will try to run it on visual studio. I  have visual studio 2017 will it work?

**Comment by Neargye** [comment]
With vs2017 work, run cmake to build project

**Comment by Neargye** [comment]
@HackersSpirit You can try folow step:
```
git clone https://github.com/Neargye/hello_tf_c_api
cd hello_tf_c_api
mkdir build
cd build
cmake -G "Visual Studio 15 2017" -A x64 ..
cmake --build . --config Debug
```

**Comment by HackersSpirit** [comment]
@Neargye : Sure will try and let you know.

**Comment by finger563** [comment]
@Neargye how did you configure / run the bazel build for generating the `.dll`, `.lib`, `.exp`, and `.def`? I've downloaded the official google release which contains only the `.dll` which I'm unable to properly compile with using vs2017, and I've not been able to figure out how to get bazel to build the windows library files

**Comment by finger563** [comment]
Ah nevermind - I figured out why my commands to turn the `.dll` into `.lib` using `dumpbin` and such weren't working - my regex to get just the names was missing some of the names :P

**Comment by Neargye** [comment]
@finger563 i use dumpbin too.
