### ISSUE TITLE
Specify device

### ISSUE THREAD

**Issue by ttdd11** [Neargye/hello_tf_c_api#13]
Thanks for this it is very helpful. Is it possible to specify a specific device for the graph (ie. gpu:0) as per the c++ api?

**Comment by Neargye** [comment]
@ttdd11 Hi
Try something like
```
TF_OperationDescription* desc = TF_NewOperation(graph, op_type, op_name);
TF_SetDevice(desc, "/gpu:0");
```

**Comment by ttdd11** [comment]
@Neargye Okay i tried this. Here is my code:

	TF_Operation* op;
	std::size_t pos = 0;

	while ((op = TF_GraphNextOperation(graph, &pos)) != nullptr) {
		const char* name = TF_OperationName(op);
		QString strName = QString(name);
		TF_OperationDescription* desc = TF_NewOperation(graph, TF_OperationOpType(op), TF_OperationName(op));
		TF_SetDevice(desc, "/gpu:0");

Has no effect of the device being used.

**Comment by Neargye** [comment]
Unfortunately, I did not try to run on GPU using this function `TF_ImportGraphDefOptionsSetDefaultDevice`
