### ISSUE TITLE
How to generated the graph.pb file

### ISSUE THREAD

**Issue by wangkuiyi** [Neargye/hello_tf_c_api#16]
Hi @Neargye , 

I am curious how did you generate the https://github.com/Neargye/hello_tf_c_api/blob/master/models/graph.pb file?

I tried to call [`tf.saved_model.Builder`](https://www.tensorflow.org/api_docs/python/tf/saved_model/Builder) as in [my sample program](https://github.com/wangkuiyi/tensorflow-go/blob/master/lr.py); it generates `exported_model/saved_model.pb`.  However, when I re-ran your [`load_graph.cpp`](https://github.com/Neargye/hello_tf_c_api/blob/master/src/load_graph.cpp) example, the import graph API failed.

I have [another program](https://github.com/wangkuiyi/tensorflow-go/blob/master/hello_tf.go) that calls the Go API, which, to my understanding, is a binding built on top of the C API, also failed at importing the graph.

Is that you created `graph.pb` not by calling `tf.saved_model.Builder` but some other API?

**Comment by Neargye** [comment]
Before work with model, needed "freeze" graph. Example: https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc

**Comment by Neargye** [comment]
Add doc how to generated the graph.pb https://github.com/Neargye/hello_tf_c_api/blob/master/doc/prepare_models.md
