### ISSUE TITLE
failed work on win10  

### ISSUE THREAD

**Issue by chuanraoCV** [Neargye/hello_tf_c_api#17]
Following your steps, win10 did not succeed. There is no symbol file loaded for tensorflow.dll.I put tensorflow.dll in the code directory

**Comment by Neargye** [comment]
Try build from cmake

**Comment by chuanraoCV** [comment]
Thank you for your reply.With cmake compilation, it still fails.
[`imge`](![image](https://user-images.githubusercontent.com/32029020/57224762-fe66a800-703c-11e9-8690-5fdb7e4c74b1.png)
)
![image](https://user-images.githubusercontent.com/32029020/57224671-c19ab100-703c-11e9-8ec2-860589d2584a.png)
``

**Comment by chuanraoCV** [comment]
When the cmake compilation is complete, running **hello_tf.cpp**  will prompt "no symbol file loaded for tensorflow.dll"
![image](https://user-images.githubusercontent.com/32029020/57225080-d592e280-703d-11e9-828f-046f19f29c7f.png)

**Comment by chuanraoCV** [comment]
Put tesorflow.dll in exe directory, run exe, will prompt
The application could not start properly (0xc0000142). Click ok to close the program.
![image](https://user-images.githubusercontent.com/32029020/57225345-b34d9480-703e-11e9-980b-73de4177702d.png)

**Comment by Neargye** [comment]
VS2017?

**Comment by chuanraoCV** [comment]
> VS2017?

yes ，win10 64+vs2017

**Comment by Neargye** [comment]
"Project"->"Properties"->Configuration Properties"->"Linker"->"Additional Dependencies" and add path to your tensorflow.lib as a next line.

Make sure that the tensorflow.dll is in Output Directory (by default, this is Debug\Release under your project's folder) or either in the directory contained by the %PATH% environment variable.
