### ISSUE TITLE
C library for Android 

### ISSUE THREAD

**Issue by dtczhl** [Neargye/hello_tf_c_api#18]
Your repo helps me a lot. I can run Tensorflow models in Ubuntu and Windows now. 
My problem is I have a system running Android, how can I generate libtensorflow.so for Android?
Could you give me some instructions? 

Thanks

**Comment by Neargye** [comment]
TFLite is a library more suitable for mobile devices.  maybe you try it for android?

**Comment by dtczhl** [comment]
Does TFLite use the same API as TF C?
I'm working on a project with a headset that runs Android OS. The SDK of that headset allows me to link to .so libraries. That's why I like to know if there is a similar libtensorflow.so for Android. 
If it is convenient for you, could you kindly add TFLite usage to your repo? 
It'll help me a lot, and I think other people would also be interested in how to use TFLite in Android.

**Comment by Neargye** [comment]
You need use tf in c++? Or in java?

**Comment by dtczhl** [comment]
In C/C++

**Comment by Neargye** [comment]
I try add my example. 
For now you can try this http://www.sanj.ai/Android-App-With-Tflite-C++-API/

**Comment by dtczhl** [comment]
Thanks very much. Could you let me know after you add your examples? 
Your tutorials are very concise and clear.

**Comment by Neargye** [comment]
Yes, I update this issues when adding android example

**Comment by dtczhl** [comment]
> Yes, I update this issues when adding android example

Hi. I'm wondering the progress of updating Tensorflow Lite. No rush though. 

BTW, your documents (doc/optimizing.md and doc/prepare_models.md) on mobile devices are detailed and very helpful. I appreciate that.

**Comment by dtczhl** [comment]
> Yes, I update this issues when adding android example

Hi. I can run TF Lite C++ in Android now, but your tutorials are still welcome. 
BTW, are you able to run batch inputs in TF Lite? 
For example, a model takes an input-length of 10. I can use Tensorflow C to feed 50 numbers, which runs 5 times of the model with a single function call (which is much faster than manually running the model 5 times). 
I see TFLite Interpreter has a function called ResizeInputTensor, which I think is for this purpose. But I got errors when I try to input more numbers. Is there anything that might easily go wrong for beginners?

**Comment by Neargye** [comment]
Hi, check this batch example https://github.com/Neargye/hello_tf_c_api/blob/master/src/batch_interface.cpp

**Comment by dtczhl** [comment]
> Hi, check this batch example https://github.com/Neargye/hello_tf_c_api/blob/master/src/batch_interface.cpp

It works, but it is for Tensorflow C. Do you have examples for TF Lite? 
Thanks.

**Comment by Neargye** [comment]
Try something like https://stackoverflow.com/questions/51576944/tensorflow-lite-for-variable-sized-input

**Comment by dtczhl** [comment]
> Try something like https://stackoverflow.com/questions/51576944/tensorflow-lite-for-variable-sized-input

I tried that before. However, my program crashes whenever I call 
```
ResizeInputTensor();
AllocateTensors();
```
even I use the exact dimensions without using batches. 
For example, my model takes input of dimensions 1, 100, 9
I tried to run
```
this->interpreter->ResizeInputTensor(this->interpreter->inputs()[0], {1, 100, 9});
this->interpreter->AllocateTensors();
```
it crashes. However, if I just call
```
this->interpreter->AllocateTensors();
```
then everything works fine. Not sure what goes wrong.

**Comment by dtczhl** [comment]
I changed Tensorflow Lite version to 2.0, which allows me to run
```
this->interpreter->ResizeInputTensor(this->interpreter->inputs()[0], {1, 100, 9});
this->interpreter->AllocateTensors();
```
Basically, nothing is changed because I just call ResizeInputTensor with original/default dimensinos. 

However, I cannot change to other dimensions. This is still an open issue here
https://github.com/tensorflow/tensorflow/issues/22377
It seems that Android Tensorflow Lite does not support it.

**Comment by Neargye** [comment]
could you please send project example, I will try myself

**Comment by dtczhl** [comment]
> could you please send project example, I will try myself

I attach my sample project below. Thanks. 
[sample project](https://www.huanlezhang.com/DataDisk/sample.zip)

**Comment by Neargye** [comment]
Hi, I do some test, it seems you are right, Android Tensorflow Lite does not support it.

**Comment by dtczhl** [comment]
> Hi, I do some test, it seems you are right, Android Tensorflow Lite does not support it.

Thanks. BTW, do you know if it works in iOS? I'm just curious about that.

**Comment by Neargye** [comment]
Hm, I can check tomorrow in iOS.

**Comment by dtczhl** [comment]
> Hm, I can check tomorrow in iOS.

Thank you. Please let me know after you check it.

**Comment by Neargye** [comment]
I could not do it on iOS.

**Comment by dtczhl** [comment]
> I could not do it on iOS.

Thanks.
