### ISSUE TITLE
How to built with mkl support?

### ISSUE THREAD

**Issue by Somdyuti2** [Neargye/hello_tf_c_api#22]
Is there any way that the we can build the library with mkl support using cmake?

**Comment by Neargye** [comment]
MKL was added as of TensorFlow 1.2 and currently only works on Linux. It also does not work when also using --config=cuda.

```
./configure
bazel build --config=mkl --config=opt ...
```

**Comment by Neargye** [comment]
only can build tf with mkl for Linux using bazel.

**Comment by Somdyuti2** [comment]
I see. Can it at least be built with the supported CPU instructions (AVX, SSE 4.2, FMA) enabled with cmake?

**Comment by Neargye** [comment]
Y need for win?

**Comment by Somdyuti2** [comment]
Maybe also on windows eventually, but even for linux need to deploy an application with TF C API within a package which has a native cmake build system.

**Comment by Neargye** [comment]
You can also build a TF, the same bazel, and then add it to the package.
