### ISSUE TITLE
cmake error  Unsupported protocol"Protocol "https"

### ISSUE THREAD

**Issue by scjaiyueliang** [Neargye/hello_tf_c_api#23]
CMake Error at CMakeLists.txt:40 (message):
  error downloading tensorflow lib: "Unsupported protocol"Protocol "https"
  not supported or disabled in libcurl

hello，I was Confused by this question, but how to solve this problem?Can you help me?

**Comment by Neargye** [comment]
Hi, cmack try downloads tensorflow lib, but ocurr error, for some reason not available https.
What OS you use?

**Comment by Neargye** [comment]
This error indicates that your CMake is linked against a libcurl with SSL disabled.

**Comment by Neargye** [comment]
try this 
https://askubuntu.com/questions/683857/curl-1-protocol-https-not-supported-or-disabled-in-libcurl
or
https://www.bountysource.com/issues/31029799-automatic-hunter-download-fails-with-protocol-https-not-supported-or-disabled-in-libcurl

**Comment by scjaiyueliang** [comment]
my os is ubuntu,  curl -V shows
curl 7.65.1 (x86_64-pc-linux-gnu) libcurl/7.65.1 OpenSSL/1.1.0g zlib/1.2.8
Release-Date: 2019-06-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

**Comment by Neargye** [comment]
[CMakeLists.txt](https://github.com/Neargye/hello_tf_c_api/files/3268425/CMakeLists.txt)
please check this cmake.

**Comment by Neargye** [comment]
what version cmake?

**Comment by scjaiyueliang** [comment]
my os is ubuntu,  curl -V shows
curl 7.65.1 (x86_64-pc-linux-gnu) libcurl/7.65.1 OpenSSL/1.1.0g zlib/1.2.8
Release-Date: 2019-06-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

**Comment by scjaiyueliang** [comment]
The second method works! thanks very much!

**Comment by scjaiyueliang** [comment]
a new problem comes,
./create_tensor 
./create_tensor: symbol lookup error: /home/Desktop/hello_tf_c_api/tensorflow/lib/libtensorflow.so: undefined symbol: _ZN10tensorflow6Device4SyncERKSt8functionIFvRKNS_6StatusEEE
why it ?do you have any ideas?

**Comment by Neargye** [comment]
What version gcc used?

**Comment by scjaiyueliang** [comment]
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
cmake version 3.6.0
now I found when it run this command sudo ./session_run,the result is right. when it run this command  ./session_run,the result is wrong.

**Comment by scjaiyueliang** [comment]
ldd session_run 
	linux-vdso.so.1 =>  (0x00007ffc67913000)
	libtensorflow.so => /home/196/Desktop/work/hello_tf_c_api/tensorflow/lib/libtensorflow.so (0x00007f4ef2201000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4ef1e7f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4ef1c69000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4ef189f000)
	libtensorflow_framework.so => /home/scj4/workspace/tf/bythirdcommon/lib64_release/libtensorflow_framework.so (0x00007f4ef0bfc000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4ef09f8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4ef07db000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4ef04d2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4ef02ca000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4efa39f000)

**Comment by scjaiyueliang** [comment]
ldd create_tensor 
	linux-vdso.so.1 =>  (0x00007ffff30cc000)
	libtensorflow.so => /home/196/Desktop/work/hello_tf_c_api/tensorflow/lib/libtensorflow.so (0x00007f17ff349000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f17fefc7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f17fedb1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f17fe9e7000)
	libtensorflow_framework.so => /home/scj4/workspace/tf/bythirdcommon/lib64_release/libtensorflow_framework.so (0x00007f17fdd44000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f17fdb40000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f17fd923000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f17fd61a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f17fd412000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f18074e7000)
