### ISSUE TITLE
win10 vs2019 tensorflow.dll not found

### ISSUE THREAD

**Issue by wangxuesong29** [Neargye/hello_tf_c_api#25]
**Hi. I had run this in my mac and windows.**

**For mac, it can work. But for windows, it complains about "tensorflow.dll not found" when I try to execute the built hello_tf.exe.**

The German is "The code cannot be run because tensorflow.dll cannot be found".

![image](https://user-images.githubusercontent.com/14146871/60329769-51037700-9991-11e9-98a8-c4caa03a8b0b.png)

![image](https://user-images.githubusercontent.com/14146871/60329284-56ac8d00-9990-11e9-97c8-946d486a6f28.png)
![image](https://user-images.githubusercontent.com/14146871/60329349-7c399680-9990-11e9-97dc-aee9f4db9459.png)
No error, but it constantly says about "no need to re-run" balabala...

**When I try to run:**
![image](https://user-images.githubusercontent.com/14146871/60329457-abe89e80-9990-11e9-884a-284e5b225950.png)

**I have checked the CMakelists.txt, it looks good. And `tensorflow` folder with `lib` and `include` are good too.**
![image](https://user-images.githubusercontent.com/14146871/60329627-071a9100-9991-11e9-9ac0-44549e5efc03.png)
![image](https://user-images.githubusercontent.com/14146871/60330035-e0108f00-9991-11e9-90d6-1b485f6fe4ef.png)

I am a bit struggling. Can you give some advices？

**Comment by wangxuesong29** [comment]
I have found out that it might happen that `C:\Users\wang\Downloads\hello_tf_c_api-master\build\Debug`  and `C:\Users\wang\Downloads\hello_tf_c_api-master\build` lack ·tensorflow.dll·. 

It is mentioned by @Neargye [here](https://github.com/Neargye/hello_tf_c_api/issues/17).
Copy and paste `tensorflow.dll` into both folders.

Now the problems solved and new problems are comming TT.

**Comment by Neargye** [comment]
Hi
First, try run

```
if exist build RMDIR /S /Q build
if exist build RMDIR /S /Q tensorflow
if not exist build mkdir build
cd build
cmake .. -G "Visual Studio 15 2017" -A x64
cmake --build . --config Debug
ctest --output-on-failure -C Debug
pause
```
