### ISSUE TITLE
how to compile tensorflow.dll

### ISSUE THREAD

**Issue by wangxuesong29** [Neargye/hello_tf_c_api#26]
Hi. 
I am not sure if I am asking a silly question: how can I compile the tensorflow source into a dll?

I googled for a whole and I tried:

System:
- Python: python 3.7
- Compiler:  Visual Studio 2019
- Tensorflow: r1.6 and r1.13

```
cmake .. -G"Visual Studio 16 2019" -Thost=x64 ^
-DCMAKE_BUILD_TYPE=Release ^
-Dtensorflow_VERBOSE=ON ^
-Dtensorflow_ENABLE_GRPC_SUPPORT=OFF ^
-Dtensorflow_BUILD_PYTHON_BINDINGS=OFF ^
-Dtensorflow_BUILD_CC_EXAMPLE=OFF ^
-Dtensorflow_BUILD_SHARED_LIB=ON ^
-Dtensorflow_ENABLE_GPU=ON ^
-DPYTHON_EXECUTABLE=C:\Users\wang\AppData\Local\Programs\Python\Python37\python.exe ^
-Dtensorflow_BUILD_SHARED_LIB=ON ^ 
-DCUDA_HOST_COMPILER="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe"
```

Then, I build
```bash
MSBuild /p:Configuration=Release /verbosity:detailed tensorflow.vcxproj
```

There are errors. I have no clues about where to start to fix.

**Comment by Neargye** [comment]
Hi, I usually do this guide https://www.tensorflow.org/install/source_windows
This week I am not with my working machine, so I can’t check it myself.

**Comment by Neargye** [comment]
Hi, How are you doing?

**Comment by wangxuesong29** [comment]
I tried `python3.7 `+ `tf 1.13` with `cmake` + `vs 2017` + `cuda10.0` + `cudnn 7`, it doesn't work. The same for `bazel`. I guess it could be the cuda10.0's problem. 

I am a bit frustrated to re-install cuda so I stop trying further. 

[tensorflow-windows-build-script](https://github.com/guikarist/tensorflow-windows-build-script) has a successful example, I am giving the last shot.

**Comment by Neargye** [comment]
For win-gpu ypu can try https://github.com/Neargye/tensorflow/releases/download/v1.14.0/libtensorflow-gpu-windows-x86_64-1.14.0.zip
