### ISSUE TITLE
GetTensorsData function error

### ISSUE THREAD

**Issue by Dinl** [Neargye/hello_tf_c_api#30]
Hi, I have just loaded a model trained in TensorFlow python, after run the session for a given input some problems happen:

1. If this function is used, good results are obtained BUT after some iterations the output size is not the same (should be 256 and I get error getting data[128]) 
`const auto data = static_cast<float*>(TF_TensorData(output_tensor));`

the output is:
`0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22.0965, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 77.3298, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 85.9351, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 190.352, 0, 0, 0, 47.3773, 0, 0, 0, 0, 114.226, 0, 0, 0, 0, 0, 0, 57.9978, 0, 0, 0, 0, 0, 0, 0, 0, 0, 66.6906, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0698555, -0.0425288, 0.251769, -0.146165, 0.0398469, 0.0603849, -0.0709948, 0.0525762, 0.0905565, -0.139356, -0.0768467, -0.106491, 0.272678, -0.00842083, -0.151077, -0.077257, 0.244632, 0.191824, 0.12273, -0.0615471, 0.0851486, -0.0163544, -0.0207504, -0.110528, 0.364326, -0.011672, -0.0672661, 0.095574, 0.195031, -0.0513856, 0.148535, 0.0222169, 0.0812069, -0.0500609, 0.167545, 0.0214508, -0.21389, 0.134474, -0.00433608, 0.00449877, -0.0329179, -0.0248889, -0.10523, -0.0159402, -0.156834, -0.0937081, 0.112361, 0.104516, 0.0367866, 0.0374388, -0.158911, -0.0944544, -0.119521, 0.1857`

2. If this function from tf_utils is used, the results are so different, there are some nan and high values.
`const auto data = tf_utils::GetTensorsData<float>(output_tensor);`

the output is:
`0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22.0965, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 77.3298, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 85.9351, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 190.352, 0, 0, 0, 47.3773, 0, 0, 0, 0, 114.226, 0, 0, 0, 0, 0, 0, 57.9978, 0, 0, 0, 0, 0, 0, 0, 0, 0, 66.6906, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.91582e+25, 0, -2.43938e+35, 0, 5.5223e+11, 0, -2.63315e+35, 0, 0, 0, -nan, 0, -2.93408e+35, 0, 3.09013e+25, 0, 0, 0, 0, 0, 1.91574e+25, 0, -2.43936e+35, 0, 0.00164726, 0, 1.75442e+12, 0, 0, 0, 0, 0, 1.91574e+25, 0, 0.00164726, 0, 0, 0, -nan, 0, -2.9095e+35, 0, 3.09015e+25, 0, 0, 0, -nan, 0, -2.92585e+35, 0, 3.09014e+25, 0, 0, 0, -2.43937e+35, 0, 1.91582e+25, 0, 5.5223e+11, 0, 0, 0, -nan, 0, -2.91753e+35, 0, 3.09014e+25, 0, 0, 0, 0, 0, 1.9159e+25, 0, -2.4394e+35, 0, 8.35422e-10, 0, -2.63228e+35, 0, 0, 0, 0, 0, 1.9159e+25, 0, 8.35422e-10, 0, 0, 0, 0, 0, 0, 0, -2.43987`

There is a issue in the GetTensorsData function?
Anybody know why the output could have different size?

**Comment by Neargye** [comment]
This is strange, GetTensorsData using inside TF_TensorData
```
template <typename T>
std::vector<T> GetTensorsData(const TF_Tensor* tensor) {
  auto data = static_cast<T*>(TF_TensorData(tensor));
  if (data == nullptr) {
    return {};
  }

  return {data, data + (TF_TensorByteSize(tensor) / TF_DataTypeSize(TF_TensorType(tensor)))};
}
```

**Comment by Dinl** [comment]
Sorry, my fault, in the testing the pb filename was changed and I thought that network has 256 output size.
Closing the issue.

**Comment by Neargye** [comment]
In any case, thank you.
I noticed how to improve the GetTensorsData.
I fixed a possible error in the new commit.

**Comment by Neargye** [comment]
Improving `GetTensorData`
```
template <typename T>
std::vector<T> GetTensorData(const TF_Tensor* tensor) {
  auto data = static_cast<T*>(TF_TensorData(tensor));
  if (data == nullptr) {
    return {};
  }

  return {data, data + TF_TensorElementCount(tensor)};
}
```
