### ISSUE TITLE
Build instructions for VS 2017-2019

### ISSUE THREAD

**Issue by VladislavAD** [Neargye/hello_tf_c_api#31]
Hi, I want to test code in VS 2017 and get compile errors. I tried to copy all code to new VS project and add session_run.cpp to it sources, also I add c_api.h tensorflow.lib folders to project paths and copy tensorflow.dll to exeecution path, but have error 
`C2065	TF_TensorElementCount: undeclared identifier	NeargyeTest	...\neargyetest\neargyetest\tf_utils.hpp	94	`
Can you provide more detailed guide how to import and compile tests using VS?

**Comment by Neargye** [comment]
Try cmake, it's creat vs proj.
```
git clone --depth 1 https://github.com/Neargye/hello_tf_c_api
cd hello_tf_c_api
mkdir build
cd build
cmake -G "Visual Studio 15 2017" -A x64 ..
cmake --build . --config Debug
```

**Comment by Neargye** [comment]
also check
https://github.com/Neargye/hello_tf_c_api/issues/25
https://github.com/Neargye/hello_tf_c_api/issues/17

**Comment by VladislavAD** [comment]
Thanks! I successfully compiled and ran your code. It's working! I hardly can find differences with my code that leaks memory every TF_SessionRun and I don't find you initialize graphdef with TF_GraphImportGraphDef, I find this in other c_api examples, seems like this is unnecessary for prediction?

**Comment by Neargye** [comment]
Leaks can be by many options, need check code line by line.

**Comment by Neargye** [comment]
Checnk tf_utils files, it's wrapper on tf c api.

**Comment by VladislavAD** [comment]
Yes, this is what I did when find this repo but find no big difference. The only thing is TF_GraphImportGraphDef that was in original code snippet I find and now I blame this method for memory leak. If you are interested in my code, I have posted [question about memory leak](https://stackoverflow.com/questions/57255656/tensorflow-1-14-0-c-api-tf-sessionrun-memory-leak) on stackoverflow.
