### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by peardox** [Neargye/hello_tf_c_api#32]
In load_graph shouldn't there be a TF_DeleteStatus(status) at about line 90?

I'm debugging my own (Pascal) code which is based on yours so want to keep everything balanced

It _looks_ like I need a TF_DeleteStatus but as you didn't do it I'm not sure

**Comment by Neargye** [comment]
Yes, you need call `TF_DeleteGraph(graph);` and `TF_DeleteStatus(status);` when not need this.
I use `SCOPE_EXIT{ TF_DeleteStatus(status); };` to auto delete status on scope exit, for more detail check https://github.com/Neargye/scope_guard.

**Comment by peardox** [comment]
Ahh, I have got it right then

Didn't know what SCOPE_GUARD did...

Thanks
