### ISSUE TITLE
question about this library

### ISSUE THREAD

**Issue by Arnold1** [Neargye/hello_tf_c_api#41]
hi,

what is the difference between this library and the official tf library https://www.tensorflow.org/install/lang_c?

it seems your library can also load a tensorflow model file - and run the scoring? how fast is it - do you have any benchmarks?

Thanks.

**Comment by Neargye** [comment]
Hi, 

It's example how to run TensorFlow lib C API on Windows, Linux and macOS(Darwin).

So it's the same fast as official lib. 
I only add some wrapper and example for more comfortable work with tf c-api.

**Comment by Arnold1** [comment]
so it also uses the libtensorflow from here https://www.tensorflow.org/install/lang_c ?

**Comment by Neargye** [comment]
> so it also uses the libtensorflow from here https://www.tensorflow.org/install/lang_c ?

Yes.

> do you have a docker container (linux) with an example available? 

No docker container.

>  how much effort is it to build a grpc server around it - which serves models like TensorFlow Serving?

I do not know, in this project only examples of native use TF.
