### ISSUE TITLE
How to create Tensor of TF_BOOL?

### ISSUE THREAD

**Issue by AvalonChang** [Neargye/hello_tf_c_api#46]
I want to create a Tensor of 1-dimensional boolean type 
I tried
`
const std::vector<std::int64_t> bool_dims = { 1 };
std::vector<bool> bool_vals(1);
bool_vals[0] = false;

std::vector<TF_Tensor*> input_tensors = { CreateTensor(TF_BOOL, bool_dims, bool_vals) }
`
Unfortunately, I found std::vector<bool> nonsupport data member function
[http://www.cplusplus.com/reference/vector/vector-bool/](url)

So I modified to
`
std::vector<TF_Tensor*> input_tensors = {  CreateTensor(TF_BOOL
    , bool_dims.data(), bool_dims.size()
    , &bool_vals[0], bool_vals.size() * sizeof(bool)) }
`

then I can successfully get an input_tensors success.
but when TF_SessionRun, I got the TF_Code = TF_INVALID_ARGUMENT

I tried to use the same model, just disable the placeholder of boolean type, it's work fine
but for some reason, I need this bool placeholder.

So, how can I correctly create a Tensor of boolean type?

Thanks for Help

**Comment by Neargye** [comment]
Hi, 
Try vector<uint8_t>, I think it can help.

**Comment by AvalonChang** [comment]
Hi Neargye

I tried vector<uint8_t>, and get a Tensor successful
but TF_Code is still as TF_INVALID_ARGUMENT when TF_SessionRun.

I believe vector<uint8_t> and vector<bool> is equivalent in this case
so I will check other parts.

Thanks for your help
