### ISSUE TITLE
Inference is running very slow on CPU 

### ISSUE THREAD

**Issue by rounakskm** [Neargye/hello_tf_c_api#48]
`
// Load graph
auto graph = tf_utils::LoadGraph("C:\\Users\\Soumya Mohanty\\Documents\\Dev\\TensorflowApplication\\frozen_inference_graph_10K_Steps.pb");
	
SCOPE_EXIT{ tf_utils::DeleteGraph(graph); };
	if (graph == nullptr) {
		//std::cout << "Can't load graph" << std::endl;
	}
	else {
		//std::cout << "Graph loaded successfully" << std::endl;
	}

	// Setup session to run inference
	auto session = tf_utils::CreateSession(graph);
	SCOPE_EXIT{ tf_utils::DeleteSession(session); }; // Auto-delete on scope exit.
	if (session == nullptr) {
		std::cout << "Can't create session" << std::endl;
	}
	else{
		std::cout << "Session setup successfully " << std::endl;
	}
	
	cv::Mat image = stack[0]; // Taking one image
	int num_dims = 4;
	std::int64_t input_dims[4] = { 1, image.rows, image.cols, 3 }; //1 is number of batch, and 3 is the no of channels.
	int num_bytes_in = image.cols * image.rows * 3; //3 is the number of channels.
	// Input tensor, and assign node that will accept input
	const std::vector<TF_Output> input_ops = { {TF_GraphOperationByName(graph, "image_tensor"), 0} };
	//const std::vector<TF_Tensor*> input_tensors = { tf_utils::CreateTensor(TF_UINT8, input_dims, num_dims, image.data, num_bytes_in) }; // tenso with data
	const std::vector<TF_Tensor*> input_tensors = { tf_utils::CreateEmptyTensor(TF_UINT8, input_dims, num_dims, num_bytes_in) }; // Doen not have image data yet
	SCOPE_EXIT{ tf_utils::DeleteTensors(input_tensors); }; // Auto-delete on scope exit.

	// Output tensor, and assign node to get output from
	std::vector<TF_Output> out_ops;
	std::vector<TF_Tensor*> output_tensors;

	out_ops.push_back({ TF_GraphOperationByName(graph, "num_detections"), 0 });
	output_tensors.push_back(nullptr);

	out_ops.push_back({ TF_GraphOperationByName(graph, "detection_classes"), 0 });
	output_tensors.push_back(nullptr);

	out_ops.push_back({ TF_GraphOperationByName(graph, "detection_boxes"), 0 });
	output_tensors.push_back(nullptr);

	out_ops.push_back({ TF_GraphOperationByName(graph, "detection_scores"), 0 });
	output_tensors.push_back(nullptr);

	SCOPE_EXIT{ tf_utils::DeleteTensors(output_tensors); }; // Auto-delete on scope exit.

	for (int i = 0; i < stack.size(); i++) {
		cv::Mat image = stack[i]; // Taking one image
		//std::cout << "rows -  " << image.rows << " cols-  " << image.cols << " channels = " << image.channels() << std::endl;
		
		tf_utils::SetTensorData(input_tensors[0], image.data, num_bytes_in);

		// Run the session
		auto code = tf_utils::RunSession(session, input_ops, input_tensors, out_ops, output_tensors);

		if (code == TF_OK) {

			float* num_detections = (float*)TF_TensorData(output_tensors[0]);
			float* detection_classes = (float*)TF_TensorData(output_tensors[1]);
			float* boxes = (float*)TF_TensorData(output_tensors[2]);
			float* scores = (float*)TF_TensorData(output_tensors[3]);

			int number_detections = (int)num_detections[0];
			int box_cnt = 0;

			frame_detection_boxes frameData; // Will hold all the data for this frame
			frameData.frameNo = i; // set frame number

			//std::cout << "Frame No: " << i << std::endl;
			for (int i = 0; i < number_detections; i++) {
				if (scores[i] >= 0.5) {
					int xmin = (int)(boxes[i * 4 + 1] * image.cols);
					int ymin = (int)(boxes[i * 4 + 0] * image.rows);
					int xmax = (int)(boxes[i * 4 + 3] * image.cols);
					int ymax = (int)(boxes[i * 4 + 2] * image.rows);
					//std::cout << "Box_" << box_cnt << "(" << scores[i] << ", " << detection_classes[i] << "): [" << xmin << ", " << ymin << ", " << xmax << ", " << ymax << "]" << std::endl;
					box_cnt++;

					
					if (detection_classes[i] == 1) { // Guide-Wire
						frameData.guideWire_raw.push_back({ (float)xmin, (float)ymin, (float)xmax, (float)ymax }); //Convert to float for non-max supression and other operations 
					}
					else if (detection_classes[i] == 2) { // Strut
						frameData.strut_raw.push_back({ (float)xmin, (float)ymin, (float)xmax, (float)ymax });
					}
				}
			}
			resultVec.push_back(frameData);
		}
		else {
			std::cout << "Error run session TF_CODE: " << code;
		}

	}`

I have a I9 CPU and inference is running very slowly. 
Any suggestions?

**Comment by Neargye** [comment]
Unfortunately, I don't know how to configure performance through the API or anything else. For me, performance has always been OK.
