### ISSUE TITLE
Multiple models inference

### ISSUE THREAD

**Issue by VladislavAD** [Neargye/hello_tf_c_api#49]
Hi, thanks for repo, it was very useful and I was able to successfuly load model and predict with it. Now i'm looking for a way to predict using several models. Is it possible to load second model using C API and use both of them for prediction?

**Comment by Neargye** [comment]
Try loading two graphs, and create a separate session for each graph.

**Comment by VladislavAD** [comment]
It seams to work but I'm not sure is this stable enough for production. I read that `session.run()` is thread safe, but what if we have multiple sessions? Is it still safe to call inference from different threads or applications? Also another problem is that I can't set `allow_growth` to sessions, just can't find example how to do it using C API. I set memory limit successfuly with help of #21 , but I don't know how to set right amount for any loaded graph. So I limit GPU memory per graph to 0.3 from all amount and I can load up to 3 models, despite I know that some graphs are smaller and perhaps some graphs can be bigger in future.

**Comment by Neargye** [comment]
Unfortunately, I have not used more than 1 graph.

**Comment by razr191120** [comment]
I have Done it multi model inf concurrently on gpu.
