### ISSUE TITLE
Latest version of tensorflow only be used VisualStudio2017 ？

### ISSUE THREAD

**Issue by taotaolin** [Neargye/hello_tf_c_api#5]
The latest version of tensorflow can only be used VisualStudio2017 ？ I am using the VisualStudio2015 hint syntax error

**Comment by Neargye** [comment]
[Build on appveyor vs2015 pass](https://ci.appveyor.com/project/Neargye/hello-tf-c-api/branch/master)


Are you compiling x64? Could you send a error message?

**Comment by taotaolin** [comment]
Now compiled, how to choose to use CPU or GPU？

**Comment by Neargye** [comment]
Different build are required with the support of CPU and GPU. My library is build with the support of the Cpu.

**Comment by taotaolin** [comment]
I can't successfully build tensorflow for GPU..View official README，Does the DEBUG version require python35d.lib ?

**Comment by taotaolin** [comment]
> Different build are required with the support of CPU and GPU. My library is build with the support of the Cpu.

Can you try to build a GPU version tensorflow？  i can't compelete it. thx

**Comment by taotaolin** [comment]
@Neargye Can you provide Python generated code for PB files, my PB file does not work properly.

**Comment by Neargye** [comment]
> Can you try to build a GPU version tensorflow？ i can't compelete it. thx
@taotaolin i add GPU build https://github.com/Neargye/tensorflow/releases/tag/v1.11.0

**Comment by Neargye** [comment]
> @Neargye Can you provide Python generated code for PB files, my PB file does not work properly.
Could you please clarify which code interests you?

**Comment by taotaolin** [comment]
> > @Neargye Can you provide Python generated code for PB files, my PB file does not work properly.
> 
> Could you please clarify which code interests you?

I want to load MNIST graph with the C++ API, but follow the link [http://jackytung8085.blogspot.com/2016/06/loading-tensorflow-graph-with-c-api-by.html](url) method, it was found that the compiler could not be successfully compiled.
I can't understand how to load my MNIST model using methods like `hello_tf_c_api/src/session_run.cpp`.

**Comment by Neargye** [comment]
https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc
