### ISSUE TITLE
3D input to model returns different output than python

### ISSUE THREAD

**Issue by rounakskm** [Neargye/hello_tf_c_api#50]
Hello,
I have a 3D image segmentation model. It takes 4 images at a time as input. input shape is (1,4,256,512,1). Where 1 is batch size 4 is number of images at a time, and image dimensions. 
All images are single channel images. 

To feed the input data I do the following: 

for (int frame = 0; frame < stack.size() - depth + 1; frame++) {
			std::vector<cv::Mat> lumen_images(depth); // 4 images at a time
			for (int num = 0; num < 4; num++) {
				int frame_num = frame + num;
				cv::Mat img_resized;
				cv::Mat img = stack[frame_num];
				cv::resize(img, img_resized, cv::Size(512, 256), 0, 0, cv::INTER_LINEAR);
				lumen_images[num] = img_resized;
			}

			cv::Mat lumen_input[4] = { lumen_images[0], lumen_images[1], lumen_images[2], lumen_images[3] };

			const std::vector<std::int64_t> dims = { 1, 4, 256, 512, 1 };
			const auto data_size = std::accumulate(dims.begin(), dims.end(), sizeof(float), std::multiplies<std::int64_t>{});
			auto lumendata = static_cast<float*>(std::malloc(data_size));
			//std::cout << "datasize " << data_size << std::endl;
			for (int i = 0; i < 4; i++) {
				for (int j = 0; j < 256; j++) {
					for (int k = 0; k < 512; k++) {
						//std::cout << i << " " << j << " " << k << " " << lumen_input[i].at<unsigned char>(j, k);//(float) 1.0 * ((unsigned char *)lumen_input[i].data)[j * 512 + k];
						lumendata[i*(256 * 512) + j * 512 + k] = (float) 1.0*lumen_input[i].at<float>(j, k);
					}
				}
			}

			// Updating input tensor with current iteration data
			tf_utils::SetTensorData(input_tensors[0], lumendata, num_bytes_in);

			// Run the session
			auto code = tf_utils::RunSession(session, input_ops, input_tensors, out_ops, output_tensors);
			//std::cout << "Code = " << code << std::endl;
			if (code == TF_OK) {
				//size_t output_size = TF_TensorByteSize(output_tensors[0]) / TF_DataTypeSize(TF_FLOAT);
				float* model_oputput = (float*)TF_TensorData(output_tensors[0]);
				for (int frameOffset = 0; frameOffset < 4; frameOffset++) {
					cv::Mat outputslice(cv::Size(512, 256), CV_32F);
					for (int i = 0; i < 256; i++) {
						for (int j = 0; j < 512; j++) {
							outputslice.at<float>(i, j) = model_oputput[512 * 256 * frameOffset + 512 * i + j];
						}
					}
					cv::namedWindow("Display window", cv::WINDOW_AUTOSIZE);
					cv::imshow("Display window", outputslice);                   
					cv::waitKey(0);

					predictionsPerSlice[frame + frameOffset].push_back(outputslice);
				}
			}
			else {
				std::cout << "Code = " << code << std::endl;
			}
			lumen_images.clear(); // Clearing the vector
		}

But the output slice is different from the output I get using python and the same weights. 

I made sure that after pre-processing the image, the pixel values of the input stack were exactly the same as that in python. But the same weights yield different results. 

What am I missing? kindly help.

Soumya

**Comment by Neargye** [comment]
Check https://github.com/Neargye/hello_tf_c_api/issues/2 and https://github.com/Neargye/hello_tf_c_api/pull/44
