### ISSUE TITLE
What is this actually doing?

### ISSUE THREAD

**Issue by svobora** [Neargye/hello_tf_c_api#51]
From the code, it seems that it only reads the Graph definition and then runs data through. However, I do not see loading pretrained weights anywhere. Am I mistaken? Is there a place to find code for reading pretrained weights?

**Comment by Neargye** [comment]
In this repo used frozen model. check https://github.com/Neargye/hello_tf_c_api/blob/master/doc/prepare_models.md and https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc

**Comment by svobora** [comment]
Thank you very much, now I get it.
