### ISSUE TITLE
TF_SessionRun with multiple outputs gives Segmentation Fault

### ISSUE THREAD

**Issue by pauperonway** [Neargye/hello_tf_c_api#52]
i clone this branch https://github.com/Neargye/hello_tf_c_api/tree/45c94e65fd80dd5715676f29baa15eb7c35f1f82
my model has two output, so modify the tf_image::TF_Model::loadModel(). 
when i save the infer result that got a Segmentation Fault, but just a output is normal. 
i find the same problem at [https://github.com/tensorflow/tensorflow/issues/22670] , i dont know how to resolve it... 
Any suggest?

**Comment by pauperonway** [comment]
@Xonxt need help...

**Comment by Xonxt** [comment]
@pauperonway could you please give a bit more detail on how you modify the `loadModel()` and what exactly does your model's output look like?

**Comment by pauperonway** [comment]
now the result is ok.
i modify a few lines like this:(FYI)
bool tf_image::TF_Model::loadModel( const std::string & path, const double gpu_memory_fraction, bool inferIO )
{
  // create an empty status;
  ...
  
  //get final_binary_output
    std::vector<std::string> outputNames;
    outputNames.clear();
    std::string binary_output_name = "net/final_binary_output";
    name = binary_output_name.c_str();
    //inputNames.push_back(binary_output_name);
    outputNames.push_back(name);
    //std::cout << "name: " << name << std::endl;

    // get last:
    while ( (op = TF_GraphNextOperation( m_pGraph, &pos )) != nullptr ) {
      name = TF_OperationName( op );
    }
    outputNames.push_back(name);
    //std::cout << "name: " << name << std::endl;

    setOutputs( { outputNames } );
    //setOutputs( { name } );
  }

  return true;
}

std::vector<cv::Mat> tf_image::TF_Model::predict_image2image( const std::vector<cv::Mat>& input )
{
  ...

  // if everything ok, parse the output:
  if ( !output_tensors.empty() ) {

    // construct the method output:
    for ( size_t i = 0; i < output_tensors.size(); i++ )
    {
      auto shape = GetTensorShape( output_tensors.at( i ) );
      if (shape[2] <= 0 || shape[2] > 3) shape[2] = 1;
      auto data = tf_utils::GetTensorsData<float>( { output_tensors.at( i ) } );

      // go through all outputs
      output.push_back( cv::Mat( static_cast<int>(shape[0]), static_cast<int>(shape[1]), CV_32FC( static_cast<int>(shape[2]) ), (void*) data[0].data() ) );
    }
  }

  return output;
}

**Comment by pauperonway** [comment]
@Xonxt the key modify should be data[i]  ---> data[0].

**Comment by pauperonway** [comment]
@Neargye hope this branch could merge to master.
