### ISSUE TITLE
Multiple GPU Inferencing

### ISSUE THREAD

**Issue by razr191120** [Neargye/hello_tf_c_api#54]
Hi @Neargye , I am using the tensorflow gpu libraries that you published. Works like a charm. 

My question is, Is there a way that we can run multi gpu inferencing? i have two graphs and two gpus and i want to run each model on a dedicated gpu, simultaneously. Please let me know if there is a way..  thanks

**Comment by VladislavAD** [comment]
I'm interested in multiple GPU inference too. I found this code:
``` 
auto opts = TF_NewImportGraphDefOptions();
std::string device = "/device:GPU:" + std::to_string(gpu_number);
TF_ImportGraphDefOptionsSetDefaultDevice(opts, device.c_str());
```
to place before `TF_GraphImportGraphDef` and it seems that my two graphs are placed into different GPU's according to nvidia-smi but now I'm having another problems:
1) I'm not sure inference is simultaneous
2) each graph take 4GB of RAM, I think they should go into GPU RAM instead, maybe something isn't deallocated?
