### ISSUE TITLE
Why GPU is slower than CPU

### ISSUE THREAD

**Issue by ppeng** [Neargye/hello_tf_c_api#9]
hello i  tried this project .I have trained a lstm mode and i load the model to predict my data.I find the GPU is slowly than CPU.
gpu:nvidia TITAN X
CUDA：9.0
cudnn:7.0
cpu: intel E5
i predicted about 200 data and every data call the function ：
TF_SessionRun(sess,
			nullptr, // Run options.
			&input_op, &input_tensor, 1, // Input tensors, input tensor values, number of inputs.
			&out_op, &output_tensor, 1, // Output tensors, output tensor values, number of outputs.
			nullptr, 0, // Target operations, number of targets.
			nullptr, // Run metadata.
			status // Output status.
			);
every time GPU is slowly than CPU
Is my method wrong?Is there a way to increase the speed? and can I enter data in batches for prediction?
thanks

**Comment by Neargye** [comment]
I just can not say.
You should measure on your own host, the main thing is to check the speed not by a single start, TF has the property of "warming up".
